services:
  - type: web
    name: ai-diary
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    rootDir: OneDrive/Documents/Desktop/AI-Diary
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGO_DB_ATLAS
        sync: false
      - key: PORT
        value: 10000